name: 'Amazon ECS "Render Task Definition" Action for GitHub Actions'
description: 'Inserts a container image URI into a container definition in an Amazon ECS task definition JSON file, creating a new file.'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  task-definition-patch:
    description: 'The path to the ECS task definition JSON file'
    required: true
  service:
    description: 'The name of the ECS service to update'
    required: true
  cluster:
    description: 'The name of the ECS cluster'
    required: true
  container-name:
    description: 'The name of the container defined in the containerDefinitions section of the ECS task definition'
    required: true
  image:
    description: 'The URI of the container image to insert into the ECS task definition'
    required: true
outputs:
  task-definition:
    description: 'The path to the rendered task definition file'
runs:
  using: 'node12'
  main: 'dist/index.js'
