name: 'Amazon ECS "Render Task Definition" Action for GitHub Actions'
description: 'Inserts a container image URI into a container definition in an Amazon ECS task definition JSON file, creating a new file.'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  task-definition:
    description: 'The path to the ECS task definition JSON file'
    required: true
  container-name:
    description: 'The name of the container defined in the containerDefinitions section of the ECS task definition'
    required: true
  image:
    description: 'The URI of the container image to insert into the ECS task definition'
    required: true
  environment-variables:
    description: 'Variables to add to the container. Each variable is of the form KEY=value, you can specify multiple variables with multi-line YAML strings.'
    required: false
  accountId:
    description: 'AWS Account ID.'
    required: true
  region:
    description: 'AWS Region.'
    required: true
  stage:
    description: 'Current working stage (DEV, STAGING, PROD)'
    required: true
  secrets:
    description: 'Secrets to add to the container. Each variable is of the form KEY=value, you can specify multiple variables with multi-line YAML strings.'
    required: false
outputs:
  task-definition:
    description: 'The path to the rendered task definition file'
runs:
  using: 'node12'
  main: 'dist/index.js'
