on:
  push:
    branches:
      - integ-tests

name: Integration Test

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Print current build ID
      run: |
        echo Integration test run: BUILD_ID

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Render Amazon ECS task definition with task definition file
      id: render-task-definition-file
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: sample-app
        image: amazon/amazon-ecs-sample:latest

    - name: Validate Amazon ECS task definition file
      env:
        TASK_DEF_FILE: ${{ steps.render-task-definition-file.outputs.task-definition }}
      run: |
        diff expected-task-definition.json $TASK_DEF_FILE

    - name: Register Amazon ECS task definition file
      env:
        TASK_DEF_FILE: ${{ steps.render-task-definition-file.outputs.task-definition }}
      run: |
        aws ecs register-task-definition --cli-input-json file://$TASK_DEF_FILE

    - name: Render Amazon ECS task definition with task definition arn (amazon resource name)
      id: render-task-definition-arn
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition-arn: task-definition-arn
        container-name: sample-app
        image: amazon/amazon-ecs-sample:latest

    - name: Render Amazon ECS task definition with task definition family
      id: render-task-definition-family
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition-family: task-definition-family
        container-name: sample-app
        image: amazon/amazon-ecs-sample:latest

    - name: Render Amazon ECS task definition with task definition family and revision
      id: render-task-definition-family-revision
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition-family: task-definition-family
        task-definition-revision: 1
        container-name: sample-app
        image: amazon/amazon-ecs-sample:latest