on:
  push:
    branches:
      - integ-tests

name: Integration Test

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Print current build ID
      run: |
        echo Integration test run: BUILD_ID

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Render Amazon ECS task definition with task definition file 
      id: render-task-definition-file
      uses: shesaave/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: sample-app
        image: amazon/amazon-ecs-sample:latest

    - name: Render Amazon ECS task definition with task definition arn (amazon resource name)
      id: render-task-definition-arn
      uses: shesaave/amazon-ecs-render-task-definition@v1
      with:
        task-definition-arn: arn:aws:ecs:us-west-2:851725652419:task-definition/fetch-def-task-definition:16
        container-name: fetch-app
        image: amazon/amazon-ecs-sample:latest

    - name: Render Amazon ECS task definition with task definition family 
      id: render-task-definition-family
      uses: shesaave/amazon-ecs-render-task-definition@v1
      with:
        task-definition-family: fetch-def-task-definition
        container-name: fetch-app
        image: amazon/amazon-ecs-sample:latest

    - name: Render Amazon ECS task definition with task definition family and revision
      id: render-task-definition-family-revision
      uses: shesaave/amazon-ecs-render-task-definition@v1
      with:
        task-definition-family: fetch-def-task-definition
        task-definition-revision: 1
        container-name: fetch-app
        image: amazon/amazon-ecs-sample:latest

    - name: Deploy Amazon ECS task definition with ECS Service
      uses: aws-actions/amazon-ecs-deploy-task-definition@abe77ebded86b685c231c58bd5936280c6fcc011
      with:
        task-definition: ${{ steps.render-task-definition-arn.outputs.task-definition }}
        service: fetch-def-service
        cluster: fetch-def-cluster
        wait-for-service-stability: true

   