on:
  [pull_request]

name: Check

jobs:
  check:
    name: Run Unit Tests
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      #Version actions/checkout@V3.6.0
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
    - name: Node setup
      #Version actions/setup-node@v3.8.1
      uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d
      with:
        node-version: "18.16.1"
    - name: Run tests
      run: |
        npm ci
        npm test
  conventional-commits:
    name: Semantic Pull Request
    runs-on: ubuntu-22.04
    steps:
      - name: validate
        uses: actions/github-script@v6
        with:
          script: |
            // See https://gist.github.com/marcojahn/482410b728c31b221b70ea6d2c433f0c#file-conventional-commit-regex-md
            const regex = /^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\([\w\-\.]+\))?(!)?: ([\w ])+([\s\S]*)/g;
            const pr = context.payload.pull_request;
            const title = pr.title;
            if (title.match(regex) == null) {
              throw `PR title "${title}"" does not match conventional commits from https://www.conventionalcommits.org/en/v1.0.0/`
            }
